import { deepCopy } from "./deep-copy";
import { plusCopy } from "./plus-copy";
import { localePath, locales, type Locale } from "./i18n";
import { ReportRecovery } from "./ReportRecovery";
import { AnalyticsSettings } from "./Analytics";
import { SupportForm } from "./SupportForm";
import { CurrencyEstimate } from "./CurrencyEstimate";

export const commerceSlugs = ["privacy", "terms", "refund", "pricing", "about", "contact"] as const;
export type CommerceSlug = typeof commerceSlugs[number];
export const commerceLabels: Record<Locale, Record<CommerceSlug, string>> = {
  en: { privacy: "Privacy", terms: "Terms", refund: "Refunds", pricing: "Pricing", about: "About", contact: "Contact" },
  pt: { privacy: "Privacidade", terms: "Termos", refund: "Reembolsos", pricing: "Preços", about: "Sobre", contact: "Contato" },
  es: { privacy: "Privacidad", terms: "Términos", refund: "Reembolsos", pricing: "Precios", about: "Acerca de", contact: "Contacto" },
  ru: { privacy: "Конфиденциальность", terms: "Условия", refund: "Возвраты", pricing: "Цены", about: "О проекте", contact: "Контакты" },
  zh: { privacy: "隐私政策", terms: "使用条款", refund: "退款政策", pricing: "定价", about: "关于", contact: "联系我们" },
};

const content: Record<Locale, Record<CommerceSlug, string[]>> = {
  en: {
    privacy: ["No account is required. The quiz scores your answers in this browser. A political result can reveal sensitive information: we do not describe this service as anonymous.", "Saving a share link is optional and requires your consent. We store encrypted axis scores, quiz length and a public preview image for one year. Sharing publishes your result and image to anyone with the link; social platforms may fetch and cache them. A random link allows anyone who has it to view the free result. Links do not contain scores, experimental assignments or paid report credentials.", "Buying a report requires separate consent to store an encrypted result snapshot and connect it to the order and payment email for delivery and recovery. Encryption is not anonymization. Paid reports are kept while the report service operates, unless you request deletion. Accounting records may need to be retained separately. Abandoned orders are removed after seven days.", "Cloudflare hosts the site, database and email queue and processes technical requests such as IP addresses. Stripe processes checkout and payment details, including the private return link; we do not receive full card numbers. Resend processes your delivery email and private access link. Anyone with a private report link can access it; do not post it publicly. Refunds revoke online access, but cannot remove a PDF already downloaded.", "Google Analytics loads only after you choose to allow it. We send a cleaned page path and interaction events, not answers, axis scores, ideology labels, email addresses or report links. Ads personalization and Google Signals are disabled in the tag. This release loads no advertising network. Consent is stored in your browser; you can change it below. We count payment outcomes in the order database, not as proof that a report page was opened.", "Use Contact to request access, correction, deletion or withdrawal of result-storage consent. Include only the email or link needed to identify your record, never individual answers. Deletion of a saved result prevents later recovery. Effective 10 October 2026."],
    terms: ["12axes.net is an independent educational comparison tool. Its result is not a diagnosis, a scientific measurement, proof of affiliation or a recommendation to support any person or movement. Scores reflect questionnaire answers and the model used at that time.", "The quiz and existing basic results remain free. The optional report is a one-time purchase for one result; no account or subscription is required. Before payment, review the report description, currency and Refunds page. Do not purchase on behalf of another person without their permission to process their result.", "Private report access is provided while this service operates, with local PDF saving available in your browser. Keep a local copy. Access can end after a refund or deletion request. Applicable consumer rights remain unaffected. "],
    refund: ["For the optional one-time report, you may request a full refund within seven calendar days of purchase without giving a reason. This voluntary policy does not limit any longer rights under applicable law. A delivery failure can also be reported here.", "Use the form below with the payment email and order reference if available. Do not send card numbers or political answers. Refunds return to the original payment method; bank processing times and exchange-rate differences vary. After a successful full refund, online report access is revoked. Previously saved files cannot be recalled. Refunding an upgrade restores the remaining paid tier. Refunding the original purchase or an earlier upgrade also removes access to upgrades that depend on it; contact us to review refunds for the related charges together."],
    pricing: ["Free: 36, 60 and 240-question modes, 12-axis percentages, existing ideology/country/personality results, and optional share links. No subscription is required.", "Optional report: US$4.99 once for one result, including an axis reading guide, the top 10 ideology matches when available, a private report link, email recovery and a view that can be printed or saved as PDF. No claimed national population averages, no false discount or permanent-access guarantee.", "The charge is in USD. Bank conversion charges or taxes may apply; the checkout page shows the charge currency and amount. Localized pages show dated BRL, EUR, RUB or CNY reference estimates when available. Language does not determine your country or card currency; these are not the final card charge."],
    about: ["12axes.net is an independent project and is not affiliated with Vercel or the operator of 12axes.vercel.app. It presents political preference questionnaires as educational comparisons.", "Results compare your answers with reference profiles using our locally hosted matching calculation. Country matches refer to modeled political profiles, not averages measured from the population. Match percentages are similarity scores, not probabilities or scientific certainty."],
    contact: ["Use this private support form for report access, refund or data requests. Include your payment email and order reference if available. Do not include political answers, full card numbers or identity documents.", "Your request is saved for the site operator to review. A receipt on this page confirms submission, not that a refund has already been issued. You can recover an existing paid report below."],
  },
  pt: {
    privacy: ["O teste não exige conta. As respostas são pontuadas neste navegador. O resultado político pode revelar dados sensíveis; não chamamos este serviço de anônimo.","Compartilhar é opcional e exige consentimento. Guardamos percentuais, tamanho do teste e imagem de prévia criptografados por um ano. O resultado e a imagem ficam públicos para quem tiver o link; redes sociais podem consultá-los e manter cópias em cache. Qualquer pessoa com o link aleatório pode ver o resultado gratuito. O link não contém pontuações, grupo experimental nem acesso ao relatório pago.","Comprar exige consentimento separado para guardar uma cópia criptografada do resultado ligada ao pedido e email de pagamento. Criptografia não é anonimização. Relatórios pagos são guardados enquanto o serviço operar, salvo pedido de exclusão; registros contábeis podem exigir retenção separada. Pedidos abandonados são apagados em sete dias.","Cloudflare hospeda site, banco e fila e processa dados técnicos como IP. Stripe processa pagamento e o link privado de retorno; não recebemos números completos de cartão. Resend processa email e link privado. Quem tiver esse link poderá abrir o relatório. Reembolso revoga acesso online, mas não apaga PDFs já salvos.","Google Analytics só carrega com sua permissão. Enviamos caminho limpo da página e eventos, sem respostas, pontuações, rótulos ideológicos, emails ou links privados. O código desativa personalização de anúncios e Google Signals. Esta versão não carrega redes de publicidade. Você pode mudar a escolha abaixo.","Use Contato para acesso, correção, exclusão ou retirada de consentimento. Envie só o necessário para identificar o registro, nunca respostas. A exclusão impede recuperação futura. Em vigor a partir de 10 de outubro de 2026."],
    terms: ["12axes.net é uma comparação educativa independente, não diagnóstico, medição científica, filiação ou endosso. Os resultados dependem das respostas e do modelo utilizado.","O teste e os resultados básicos existentes continuam grátis. O relatório opcional é uma compra única para um resultado, sem assinatura ou conta. Revise descrição, moeda e reembolso antes de pagar. Não compre para outra pessoa sem autorização para processar o resultado.","Acesso privado disponível enquanto o serviço operar. Salve uma cópia em PDF. Reembolso ou exclusão encerra o acesso, sem limitar direitos legais. "],
    refund: ["Você pode pedir reembolso integral do relatório em até sete dias corridos da compra, sem justificar. Esta política não reduz direitos mais amplos previstos em lei. Falhas na entrega também podem ser relatadas aqui.","Use o formulário com email do pagamento e referência do pedido, se disponível. Não envie cartão nem respostas políticas. O reembolso vai ao método original; prazos bancários e câmbio variam. Após reembolso integral, o acesso online é revogado; arquivos já salvos não podem ser recolhidos. Reembolsar um upgrade restaura o plano pago restante. O reembolso da compra original ou de um upgrade anterior também desativa upgrades dependentes; entre em contato para revisar os reembolsos das cobranças relacionadas em conjunto."],
    pricing: ["Grátis: testes de 36, 60 e 240 perguntas, percentuais dos 12 eixos, resultados básicos existentes de ideologia, país e personalidade e links opcionais. Sem assinatura.","Relatório opcional: US$ 4,99 por um resultado. Guia dos eixos, 10 ideologias quando disponíveis, link privado, recuperação por email e versão para imprimir ou salvar em PDF. Sem supostas médias nacionais nem descontos fictícios.","Cobrança em USD. Seu banco pode cobrar câmbio e tributos; a página de pagamento mostra moeda e valor. A estimativa em reais, quando disponível abaixo com fonte e data, é apenas uma referência, não o valor final no cartão."],
    about: ["12axes.net é independente e não tem vínculo com Vercel ou com o operador de 12axes.vercel.app. Questionários de preferências políticas são apresentados como comparações educativas.","Comparamos suas respostas com perfis de referência usando um cálculo hospedado neste site. Países representam perfis políticos modelados, não médias medidas da população. Percentuais de compatibilidade são similaridades, não probabilidades ou certeza científica."],
    contact: ["Use o formulário privado para acesso a relatórios, reembolsos e pedidos de dados. Informe email do pagamento e referência do pedido, se disponível. Não envie respostas políticas, cartão completo ou documentos.","O pedido é guardado para análise do operador. A confirmação significa que foi enviado, não que o reembolso foi concluído. Você também pode recuperar um relatório pago abaixo."],
  },
  es: {
    privacy: ["No necesitas cuenta. Las respuestas se calculan en este navegador. El resultado político puede revelar datos sensibles; no lo llamamos un servicio anónimo.","Compartir requiere tu consentimiento. Guardamos puntuaciones, longitud del test e imagen de vista previa cifradas durante un año. El resultado y la imagen son públicos para quien tenga el enlace; las redes sociales pueden consultarlos y almacenarlos en caché. Cualquiera con el enlace aleatorio ve el resultado gratuito; no incluye puntuaciones, grupo experimental ni acceso pagado.","La compra requiere consentimiento separado para guardar el resultado cifrado, asociado al pedido y email de pago para entrega y recuperación. Cifrar no anonimiza. Guardamos informes mientras opere el servicio o hasta solicitar borrado; los registros contables pueden conservarse por separado. Pedidos abandonados: siete días.","Cloudflare aloja el sitio y los datos técnicos. Stripe procesa pagos y el enlace privado de retorno, sin enviarnos números completos de tarjeta. Resend procesa email y enlace privado. Cualquiera con este enlace puede abrir el informe. Un reembolso revoca acceso online, no archivos descargados.","Google Analytics carga sólo con permiso y recibe rutas limpias y eventos, sin respuestas, puntuaciones, etiquetas, emails o enlaces. El código desactiva personalización publicitaria y Google Signals. Esta versión no carga redes de anuncios. Cambia tu elección abajo.","Solicita acceso, corrección, eliminación o retirada de consentimiento mediante Contacto. No envíes respuestas. El borrado impide recuperación futura. En vigor desde el 10 de octubre de 2026."],
    terms: ["12axes.net es una comparación educativa independiente, no diagnóstico, medición científica, prueba de afiliación ni recomendación. Los resultados reflejan respuestas y modelo.","El test y los resultados básicos existentes son gratuitos. El informe es una compra única por resultado, sin cuenta ni suscripción. Revisa moneda, contenido y reembolsos antes de pagar. No proceses resultados ajenos sin permiso.","El enlace privado funciona mientras opere el servicio; guarda una copia PDF. Reembolso o borrado retira acceso sin limitar derechos legales. "],
    refund: ["Puedes solicitar devolución completa dentro de siete días naturales sin dar un motivo. Esta política no reduce derechos legales más amplios. Informa aquí cualquier fallo de entrega.","Usa el email de pago y referencia del pedido. No envíes tarjetas ni respuestas políticas. Devolvemos al método original; tiempos y cambio bancarios varían. La devolución completa revoca acceso online, no elimina archivos guardados. Reembolsar una mejora restaura el nivel pagado restante. Reembolsar la compra original o una mejora anterior también desactiva las mejoras dependientes; contacta con nosotros para revisar juntos los reembolsos de los cargos relacionados."],
    pricing: ["Gratis: tests de 36, 60 y 240 preguntas, porcentajes de los 12 ejes, resultados básicos existentes y enlaces opcionales. Sin suscripción.","Informe opcional: 4,99 USD una vez por resultado. Guía por ejes, 10 ideologías cuando estén disponibles, enlace privado, recuperación y vista imprimible/PDF. Sin medias nacionales no verificadas ni descuentos ficticios.","Cargo en USD. Tu banco puede añadir cambio e impuestos. El pago muestra moneda e importe. Los precios en euros son estimaciones de referencia con fecha, no el cargo final en tu tarjeta. El idioma no determina tu país ni la moneda de tu tarjeta."],
    about: ["12axes.net es independiente de Vercel y del operador de 12axes.vercel.app. Ofrece comparaciones educativas de preferencias políticas.","Comparamos tus respuestas con perfiles de referencia mediante un cálculo alojado en este sitio. Los países representan perfiles políticos modelados, no medias medidas de la población. La compatibilidad expresa similitud, no probabilidad ni certeza científica."],
    contact: ["Formulario privado para acceso, devoluciones o solicitudes de datos. Incluye email de pago y referencia si la tienes. No envíes respuestas, tarjetas completas ni documentos de identidad.","Tu solicitud se guarda para revisión. La confirmación no significa que ya se haya emitido un reembolso. También puedes recuperar un informe comprado abajo."],
  },
  ru: {
    privacy: ["Аккаунт не нужен; ответы обрабатываются в этом браузере. Политический результат может раскрывать чувствительную информацию, поэтому сервис не называется анонимным.","Для публикации ссылки нужно согласие. Зашифрованные баллы, длина теста и изображение для предпросмотра хранятся год. Результат и изображение доступны всем, у кого есть ссылка; социальные сети могут загружать и кешировать их. Случайная ссылка открывает бесплатный результат любому получателю, но не содержит баллов, группы эксперимента или платного доступа.","Покупка требует отдельного согласия на хранение зашифрованного результата со связью с заказом и email. Шифрование не является анонимизацией. Отчёт хранится, пока работает сервис, либо до запроса удаления; бухгалтерские записи могут храниться отдельно. Незавершённые заказы удаляются через семь дней.","Cloudflare обрабатывает технические запросы и хранит данные; Stripe обрабатывает оплату и приватную ссылку возврата без передачи нам полного номера карты; Resend доставляет приватную ссылку на email. Любой получатель ссылки может открыть отчёт. Возврат отменяет онлайн-доступ, но не удаляет скачанный PDF.","Google Analytics загружается только с согласия и получает очищенный путь и события, без ответов, баллов, ярлыков, email и ссылок. Рекламная персонализация и Google Signals отключены в коде. Рекламные сети не загружаются. Настройки можно изменить ниже.","Для доступа, исправления, удаления и отзыва согласия используйте Контакты. Не отправляйте ответы. Удалённый результат нельзя восстановить. Действует с 10 октября 2026 года."],
    terms: ["12axes.net — независимое учебное сравнение, не диагноз, научная оценка, подтверждение членства или рекомендация. Результат зависит от ответов и модели.","Тест и существующие базовые результаты бесплатны. Отчёт — разовая покупка для одного результата, без подписки. До оплаты проверьте содержание, валюту и возвраты. Нельзя обрабатывать чужой результат без разрешения.","Приватный доступ действует, пока работает сервис. Сохраните PDF. Возврат или удаление прекращают доступ, не ограничивая законные права. "],
    refund: ["Полный возврат можно запросить в течение семи календарных дней без объяснения причины. Более широкие законные права сохраняются. Здесь можно сообщить о недоставленном отчёте.","Укажите email оплаты и номер заказа. Не отправляйте карты или политические ответы. Средства возвращаются исходным способом; сроки и курс банка различаются. Полный возврат отменяет онлайн-доступ; сохранённые файлы остаются у вас. Возврат за повышение тарифа восстанавливает оставшийся оплаченный уровень. Возврат за исходную покупку или предыдущее повышение также отключает зависимые повышения; свяжитесь с нами для совместного рассмотрения возвратов по связанным платежам."],
    pricing: ["Бесплатно: 36, 60 и 240 вопросов, 12 осей, существующие базовые совпадения и необязательные ссылки. Без подписки.","Отчёт: 4,99 USD за один результат. Пояснения осей, 10 идеологий при доступности, приватная ссылка, восстановление и печать/PDF. Без недоказанных национальных средних и фиктивных скидок.","Платёж в USD. Банк может добавить комиссии и налоги. Цена в рублях — справочная оценка с датой, а не итоговое списание. Язык не определяет страну или валюту карты; возможность оплаты зависит от карты и платёжного провайдера."],
    about: ["12axes.net не связан с Vercel или оператором 12axes.vercel.app. Это учебный проект для сравнения политических предпочтений.","Ответы сравниваются с эталонными профилями при помощи расчёта на этом сайте. Страны представлены моделями политических профилей, а не измеренными средними населения. Совпадение означает сходство, а не вероятность или научную достоверность."],
    contact: ["Приватная форма для доступа, возврата и запросов о данных. Укажите email оплаты и номер заказа. Не отправляйте ответы, полные номера карт или документы.","Запрос сохраняется для оператора. Подтверждение отправки не означает завершённый возврат. Ниже можно восстановить оплаченный отчёт."],
  },
  zh: {
    privacy: ["测试无需账户，逐题回答在浏览器内计分。政治倾向结果可能揭示敏感信息，我们不将这项服务称为完全匿名。","分享是可选操作，需要你的同意。我们将轴分数、题量及公开预览图片加密保存一年。分享后，持有链接的人可查看结果与图片，社交平台也可能抓取和缓存这些内容。随机分享链接允许持有人查看免费结果；链接不包含分数、实验分组或付费报告访问凭证。","购买报告需单独同意加密保存结果快照，并与订单及付款邮箱关联，用于交付和找回。加密不等于匿名化。付费报告在报告服务运营期间保存，或按你的请求删除；会计记录可能需另行保留。未完成订单七天后清理。","Cloudflare 托管网站、数据库和邮件队列，并处理 IP 等技术请求信息。Stripe 处理结账、付款及付款后的私人返回链接，我们不接收完整银行卡号。Resend 处理邮箱和私人报告链接。持有私人链接的人可查看报告，切勿公开。退款撤销在线访问，但不能删除已下载的文件。","Google Analytics 仅在同意后加载，接收清理后的页面路径和互动事件，不接收答案、分数、意识形态标签、邮箱或报告链接。代码已关闭 Google Signals 与广告个性化，本版不加载广告网络。同意选项保存在本机，可在下方修改。付款以订单数据库为准，不将打开报告误算为付款。","访问、更正、删除数据或撤回结果存储同意，请使用联系表单。只提供定位记录所需的信息，不要发送逐题回答。删除结果后不能找回。本政策自 2026 年 10 月 10 日生效。"],
    terms: ["12axes.net 是独立的教育比较工具。结果不是诊断、科学测量、政治身份认定或对人物及运动的推荐，而是对应回答与模型的概览。","测试和现有基础结果免费。可选报告按单个结果一次性购买，无需账户，没有订阅。付款前请阅读交付内容、币种与退款政策。未经本人同意，不应为他人购买并处理其政治结果。","私人链接在报告服务运营期间有效，请保存本地 PDF 副本。退款或删除请求会终止在线访问，但不限制法定消费者权利。"],
    refund: ["可选报告自购买起七个自然日内可无理由申请全额退款。这项自愿政策不缩减适用法律规定的更长期权利。交付失败也可在此反馈。","在下方提交付款邮箱及可用的订单编号。不要发送完整卡号或政治回答。退款退回原付款方式，到账时间、汇率差异以银行处理为准。成功全额退款后撤销在线报告访问；已保存的文件无法收回。升级订单退款后恢复其余有效档位；原始订单或前序升级退款也会撤销依赖它的后续升级，请联系客服一并核对关联订单的退款。"],
    pricing: ["免费：36、60、240 题测试，12 轴百分比，现有意识形态、国家和人物匹配，以及可选分享链接。没有订阅。","可选报告：单个结果一次性 US$4.99，包含逐轴阅读指南、可用时的前 10 匹配、私人报告链接、邮箱找回，以及可打印保存为 PDF 的版本。不承诺未经验证的国家人口平均值、虚假折扣或永久服务。","实际扣款为美元，银行可能另收汇兑费及税费，结账页展示金额与币种。本地化页面可显示带日期的雷亚尔、欧元、卢布或人民币参考估值；语言不代表所在国家或银行卡币种，参考价不等于最终扣款。"],
    about: ["12axes.net 为独立项目，与 Vercel 及 12axes.vercel.app 运营者无关联，旨在提供政治偏好的教育性比较。","结果由本站的匹配计算将你的回答与参考画像比较得出。国家匹配对应建模的政治画像，并非当地人口的实测平均值。匹配百分比是相似度，不是概率或科学置信度。"],
    contact: ["报告访问、退款及数据请求请通过此私人表单提交，附付款邮箱和可用的订单编号。不要提交政治回答、完整卡号或身份证明。","请求将保存供运营者处理。页面确认仅代表已提交，不代表退款已完成。下方也提供已付款报告的找回入口。"],
  },
};

const deepPrivacy: Record<Locale, string> = {
  "en": "Quiz progress and free results are saved in this browser for 30 days and can be deleted from the test screen. Anyone using this browser may access them. Deep reports additionally store your question IDs, question version and individual answers encrypted with your order, only after separate consent. This information is used for answer evidence, simulations and recovery; it is not sent to analytics or included in email bodies. Personal and Plus purchases do not store individual answers on the server. An upgraded report may include a fresh test; the original report remains accessible. Existing retention and deletion terms also apply to these answers.",
  "pt": "O progresso e os resultados gratuitos ficam neste navegador por 30 dias e podem ser excluídos na tela do teste. Quem usar este navegador poderá acessá-los. O Deep também armazena, de forma criptografada com o pedido, IDs e versão das perguntas e respostas individuais, apenas após consentimento separado. Esses dados servem para análise, simulação e recuperação; não são enviados ao Analytics nem no corpo dos e-mails. Compras Pessoal e Plus não salvam respostas individuais no servidor. Uma ampliação pode usar um novo teste; o relatório original continua disponível. As regras de retenção e exclusão também se aplicam às respostas.",
  "es": "El progreso y los resultados gratuitos se guardan en este navegador durante 30 días y pueden borrarse en la pantalla del test. Quien use este navegador podrá acceder. Deep guarda además, cifrados con el pedido, los identificadores y la versión de las preguntas y las respuestas individuales, solo con consentimiento separado. Se usan para evidencias, simulaciones y recuperación; no se envían a Analytics ni en el cuerpo de correos. Personal y Plus no guardan respuestas individuales en el servidor. Una ampliación puede usar un nuevo test; el informe original permanece accesible. Las reglas de conservación y borrado también se aplican a estas respuestas.",
  "ru": "Прогресс и бесплатные результаты хранятся в этом браузере 30 дней; их можно удалить на экране теста. Другие пользователи браузера могут получить доступ. Deep дополнительно сохраняет идентификаторы, версию вопросов и отдельные ответы в зашифрованном виде с заказом только после отдельного согласия. Они используются для обоснования, моделирования и восстановления, не отправляются в аналитику или текст писем. Personal и Plus не сохраняют отдельные ответы на сервере. Обновление может использовать новый тест; исходный отчёт остаётся доступен. Правила хранения и удаления распространяются и на ответы.",
  "zh": "测试进度与免费结果在此浏览器保存 30 天，可在测试页面删除；使用同一浏览器的人可能访问。Deep 在单独征得同意后，另将题目编号、题库版本与逐题答案和订单关联加密保存，用于答案依据、模拟与找回，不发送至分析服务或邮件正文。基础及 Plus 订单不在服务端保存逐题答案。升级可使用新测试，原报告仍可访问。现有保存期限与删除规则同样适用于这些答案。"
};

const measurementPrivacy: Record<Locale, string> = {
  en: "With analytics consent, Google Analytics receives the external source domain without its page path, query or fragment; same-site and Stripe payment sources are excluded. A random test measurement ID is created only after consent, is not derived from answers, and connects the observed progress stages of one test. We also measure whether you continue with extra questions, result actions and checkout outcomes. Confirmed purchases include a random transaction ID, amount, currency and report tier. Opening or recovering a report does not create another purchase. Separately opting in to ad measurement allows Google Ads click and campaign identifiers to be used to attribute purchases. No answers, scores, political labels, email addresses or private report links are sent. Google Signals, personalized ads, customer matching and remarketing are disabled. You can reset these choices below. Browser consent and blocking mean measured purchases may be fewer than actual orders; refunds are reconciled against payment records.",
  pt: "Com consentimento de análise, o Google Analytics recebe o domínio de origem externo, sem caminho da página, parâmetros ou fragmento; origens do próprio site e de pagamentos Stripe são excluídas. Um ID aleatório de medição do teste é criado somente após o consentimento, não deriva das respostas e conecta as etapas de progresso observadas de um teste. Também medimos a escolha de responder perguntas extras, ações no resultado e etapas do pagamento. Compras confirmadas incluem um ID aleatório da transação, valor, moeda e tipo de relatório. Abrir ou recuperar um relatório não gera outra compra. A opção separada de medição de anúncios permite usar identificadores de cliques e campanhas do Google Ads para atribuir compras. Não enviamos respostas, pontuações, rótulos políticos, emails ou links privados. Google Signals, anúncios personalizados, listas de clientes e remarketing ficam desativados. Você pode redefinir suas escolhas abaixo. Consentimento e bloqueios podem reduzir as compras medidas; os reembolsos são conferidos nos registros de pagamento.",
  es: "Con consentimiento de analítica, Google Analytics recibe el dominio de origen externo sin ruta, parámetros ni fragmento; se excluyen los orígenes del propio sitio y de pagos de Stripe. Un ID aleatorio de medición del test se crea solo después del consentimiento, no deriva de las respuestas y conecta las etapas de progreso observadas de un test. También medimos la elección de responder preguntas adicionales, las acciones en el resultado y las etapas del pago. Las compras confirmadas incluyen un ID aleatorio de transacción, importe, moneda y tipo de informe. Abrir o recuperar un informe no genera otra compra. La opción separada de medición de anuncios permite usar identificadores de clics y campañas de Google Ads para atribuir compras. No enviamos respuestas, puntuaciones, etiquetas políticas, emails ni enlaces privados. Google Signals, anuncios personalizados, listas de clientes y remarketing están desactivados. Puedes restablecer tus opciones abajo. El consentimiento y los bloqueos pueden reducir las compras medidas; los reembolsos se cotejan con los registros de pago.",
  ru: "При согласии на аналитику Google Analytics получает домен внешнего источника без пути страницы, параметров и фрагмента; переходы с самого сайта и платёжных страниц Stripe исключаются. Случайный идентификатор измерения теста создаётся только после согласия, не выводится из ответов и связывает наблюдаемые этапы одного теста. Мы также измеряем выбор дополнительных вопросов, действия с результатом и этапы оплаты. Подтверждённые покупки включают случайный ID транзакции, сумму, валюту и тариф отчёта. Повторное открытие или восстановление отчёта не считается новой покупкой. Отдельное согласие на оценку рекламы разрешает использовать идентификаторы кликов и кампаний Google Ads для атрибуции покупок. Ответы, баллы, политические ярлыки, email и приватные ссылки не передаются. Google Signals, персонализация рекламы, списки клиентов и ремаркетинг отключены. Настройки можно сбросить ниже. Из-за согласия и блокировок измеренных покупок может быть меньше реальных; возвраты сверяются с платёжными записями.",
  zh: "同意分析后，Google Analytics 会收到外部来源域名，不包含来源页面路径、参数或片段；本站及 Stripe 付款返回来源会被排除。用于连接同一次测试中已观察进度阶段的随机测量标识，只在同意后生成，不由答案派生。我们也衡量是否继续答附加题、结果页操作和结账步骤。已确认付款的测量包含随机交易编号、实付金额、币种和报告档位。重复打开或找回报告不会新增购买。另行同意广告效果衡量后，Google Ads 的点击及广告系列标识可用于购买归因。不发送答案、分数、政治标签、邮箱或私人报告链接。Google Signals、广告个性化、客户名单匹配和再营销保持关闭。可在下方重置选择。受用户同意和浏览器拦截影响，测得的购买可能少于实际订单；退款以支付记录核对。",
};

export function commerceMeta(locale: Locale, slug: CommerceSlug) {
  const h1 = commerceLabels[locale][slug];
  return { title: h1 + " — 12Axes", h1, description: content[locale][slug][0], lead: "12axes.net · " + (slug === "privacy" ? "2026-10-10" : "2026-10-07") };
}

export function CommercePage({ locale, slug }: { locale: Locale; slug: CommerceSlug }) {
  return <main className="seo-shell">
    <header className="site-header"><a className="logo" href={localePath(locale)}><b>12</b><span>axes</span></a><div className="language-links">{locales.map((item) => <a key={item} href={localePath(item, "/" + slug)}>{item.toUpperCase()}</a>)}</div></header>
    <article className="seo-article commerce-article"><h1>{commerceLabels[locale][slug]}</h1><p className="seo-lead">{commerceMeta(locale, slug).lead}</p>{content[locale][slug].map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
      {slug === "privacy" && <><p>{deepPrivacy[locale]}</p><p>{measurementPrivacy[locale]}</p><AnalyticsSettings locale={locale} /></>}
      {slug === "pricing" && <><CurrencyEstimate locale={locale} /><section className="pricing-plus"><h2>{plusCopy[locale].plus} · {plusCopy[locale].price}</h2><CurrencyEstimate locale={locale} amount={9.99} /><p>{plusCopy[locale].includes}</p><ul>{plusCopy[locale].features.map((feature) => <li key={feature}>{feature}</li>)}</ul><p>{deepCopy[locale].plusExtra}</p><p>{plusCopy[locale].notice}</p><p>{plusCopy[locale].upgradeNote}</p><CurrencyEstimate locale={locale} amount={5} /></section><section className="pricing-plus"><h2>{deepCopy[locale].name} · {deepCopy[locale].amount}</h2><CurrencyEstimate locale={locale} amount={14.99} /><p>{deepCopy[locale].includes}</p><ul>{deepCopy[locale].features.map(feature => <li key={feature}>{feature}</li>)}</ul><p>{deepCopy[locale].needsQuiz}</p><p>{deepCopy[locale].upgradeNote}</p><p>{deepCopy[locale].consent}</p><a className="primary-button" href={localePath(locale)}>{deepCopy[locale].takeTest}</a></section></>}
      {["contact", "refund", "privacy"].includes(slug) && <SupportForm locale={locale} />}
      {["contact", "refund"].includes(slug) && <ReportRecovery locale={locale} />}
    </article>
    <footer><a href={localePath(locale)}>12Axes</a><nav>{commerceSlugs.map((item) => <a key={item} href={localePath(locale, "/" + item)}>{commerceLabels[locale][item]}</a>)}</nav></footer>
  </main>;
}
