import type { Locale } from "./i18n";
const readings: Record<Locale, string[][]> = {
  en: [
    ["Your answers lean toward public ownership while leaving coordination to markets. Ownership and price-setting are different choices: public providers can compete, and a market does not require every asset to be privately owned.", "Your answers lean toward private ownership alongside planned coordination. Private firms can operate under public targets or allocation rules. Revisit which sectors you had in mind before treating these preferences as contradictory.", "Read ownership, coordination and trade separately. A preference for one ownership model does not by itself settle how prices should be set or whether trade should cross borders."],
    ["You lean toward democratic representation and security. Elections describe how leaders are chosen; security describes the powers you allow them. Consider which limits should still bind an elected government.", "You lean toward democratic representation and individual liberty. These preferences can support each other, but majority decisions can still restrict individual rights. Identify which rights should not depend on a vote.", "Local autonomy, representation and limits on power are distinct choices. Consider the same policy at city and national level, then ask who decides and what limits apply."],
    ["Your answers combine religious leanings with support for social change. Religious belief does not automatically imply opposition to reform. Consider which beliefs are personal and which rules you would apply to everyone.", "Your answers lean toward religion and tradition. These can reinforce one another, but cultural continuity and religious authority are different reasons for a policy. Check which reason mattered in each answer.", "Religion, social change and cultural integration measure different concerns. Do not infer a person's beliefs from a preference for public rules, or assume that all forms of tradition move together."],
  ],
  pt: [
    ["Suas respostas tendem à propriedade pública com coordenação pelo mercado. Propriedade e formação de preços são escolhas diferentes: fornecedores públicos podem competir, e mercados não exigem que todos os ativos sejam privados.", "Suas respostas tendem à propriedade privada com coordenação planejada. Empresas privadas podem seguir metas ou regras públicas de alocação. Relembre os setores considerados antes de concluir que há contradição.", "Leia propriedade, coordenação e comércio separadamente. Preferir um modelo de propriedade não define sozinho a formação de preços nem a abertura comercial."],
    ["Você tende à representação democrática e à segurança. Eleições definem como líderes são escolhidos; segurança trata dos poderes concedidos. Quais limites deveriam valer também para um governo eleito?", "Você tende à representação democrática e à liberdade individual. Elas podem se apoiar, mas decisões da maioria também podem restringir direitos. Quais direitos não deveriam depender de votação?", "Autonomia local, representação e limites ao poder são escolhas distintas. Considere a mesma política no município e no país: quem decide e quais limites se aplicam?"],
    ["Suas respostas combinam religiosidade e apoio à mudança social. A fé não implica automaticamente oposição à reforma. Separe crenças pessoais de regras para todos.", "Suas respostas tendem à religião e à tradição. Elas podem se reforçar, mas continuidade cultural e autoridade religiosa são razões diferentes. Qual delas pesou em cada resposta?", "Religião, mudança social e integração cultural tratam de preocupações diferentes. Não deduza crenças pessoais apenas de preferências por regras públicas."],
  ],
  es: [
    ["Tus respuestas tienden a la propiedad pública con coordinación de mercado. Propiedad y formación de precios son decisiones distintas: proveedores públicos pueden competir y los mercados no exigen que todo sea privado.", "Tus respuestas tienden a la propiedad privada con coordinación planificada. Las empresas privadas pueden seguir objetivos públicos. Revisa los sectores que tenías en mente antes de concluir que hay contradicción.", "Lee propiedad, coordinación y comercio por separado. Un modelo de propiedad no determina por sí solo los precios ni la apertura comercial."],
    ["Tiendes a la representación democrática y a la seguridad. Las elecciones definen cómo se elige a los líderes; la seguridad trata de sus poderes. ¿Qué límites deberían respetar también los gobiernos electos?", "Tiendes a la representación democrática y a la libertad individual. Pueden reforzarse, pero la mayoría también puede restringir derechos. ¿Qué derechos no deberían depender de una votación?", "Autonomía local, representación y límites al poder son decisiones distintas. Considera la misma política a nivel local y nacional: quién decide y con qué límites."],
    ["Tus respuestas combinan inclinación religiosa y apoyo al cambio social. La fe no implica automáticamente oposición a las reformas. Separa convicciones personales de reglas para todos.", "Tus respuestas tienden a la religión y la tradición. Pueden reforzarse, pero continuidad cultural y autoridad religiosa son motivos distintos. ¿Cuál influyó en cada respuesta?", "Religión, cambio social e integración cultural plantean cuestiones distintas. No deduzcas las creencias personales solo de preferencias por normas públicas."],
  ],
  ru: [
    ["Ваши ответы сочетают общественную собственность с рыночной координацией. Владение и ценообразование — разные решения: государственные поставщики могут конкурировать, а рынок не требует частного владения всеми активами.", "Ваши ответы сочетают частную собственность с плановой координацией. Частные фирмы могут работать по общественным целям. Вспомните конкретные отрасли, прежде чем считать это противоречием.", "Рассматривайте собственность, координацию и торговлю отдельно. Форма владения сама по себе не определяет цены или открытость границ для торговли."],
    ["Вы склоняетесь к демократическому представительству и безопасности. Выборы определяют способ выбора лидеров, а безопасность — их полномочия. Какие ограничения должны связывать даже избранную власть?", "Вы склоняетесь к демократии и личной свободе. Они могут поддерживать друг друга, но большинство также может ограничивать права. Какие права не должны зависеть от голосования?", "Местная автономия, представительство и ограничения власти — разные вопросы. Рассмотрите одну политику на местном и национальном уровне: кто решает и какие границы установлены?"],
    ["Ваши ответы сочетают религиозность с поддержкой социальных изменений. Вера не означает автоматического неприятия реформ. Разделите личные убеждения и правила для всех.", "Вы склоняетесь к религии и традиции. Они могут усиливать друг друга, но культурная преемственность и религиозный авторитет — разные основания. Какое повлияло на каждый ответ?", "Религия, социальные изменения и культурная интеграция затрагивают разные вопросы. Не выводите личные убеждения только из предпочтений в общественных правилах."],
  ],
  zh: [
    ["你的回答同时倾向公共所有制与市场协调。谁拥有资产和如何形成价格是两种选择：公共服务提供者也可以竞争，市场机制也不要求所有资产都归私人。", "你的回答同时倾向私营所有制与计划协调。私营企业也可以在公共目标或资源配置规则下运作。判断是否矛盾前，先回顾答题时想到的是哪些行业。", "请分别理解所有制、资源协调与贸易。支持某种所有制，并不能单独决定价格应如何形成，或贸易是否应跨越国界。"],
    ["你的回答同时倾向民主代表与安全。选举回答如何选出领导者，安全轴涉及允许他们行使哪些权力。即使政府由选举产生，你仍希望哪些限制约束它？", "你的回答同时倾向民主代表与个人自由。两者可以互相支持，但多数人的决定也可能限制个人权利。哪些权利不应由投票决定？", "地方自治、政治代表与权力边界是不同选择。把同一项政策分别放在城市和国家层面，思考谁应决定，以及需要哪些限制。"],
    ["你的回答同时表现出宗教倾向与支持社会变迁。宗教信念不自动意味着反对改革。请区分个人信仰与希望所有人遵守的公共规则。", "你的回答同时倾向宗教与传统。它们可能互相支持，但维护文化延续和尊重宗教权威是不同理由。每条回答中，真正起作用的是哪一种？", "宗教、社会变迁与文化融合关注不同问题。不能仅凭对公共规则的偏好推断个人信仰，也不能假设各种传统必然同向变化。"],
  ],
};
export function crossAxisReading(axes: number[], locale: Locale, group: number) {
  const choice = group === 0 ? axes[6] >= 55 && axes[7] <= 45 ? 0 : axes[6] <= 45 && axes[7] >= 55 ? 1 : 2 : group === 1 ? axes[1] >= 55 && axes[2] >= 55 ? 0 : axes[1] >= 55 && axes[2] <= 45 ? 1 : 2 : axes[9] <= 45 && axes[10] >= 55 ? 0 : axes[9] <= 45 && axes[10] <= 45 ? 1 : 2;
  return readings[locale][group][choice];
}
