import type { Locale } from "./i18n";

const en = {
  name: "Deep Report", amount: "US$14.99", includes: "Everything in Report Plus, plus:", features: ["Question-by-question evidence for every axis", "Cross-axis interpretation of your positions", "Interactive answer-change exploration", "Personal reading and reflection plan"],
  plusExtra: "Search any profile; browse countries and people by category",
  consent: "For Deep, I also agree to encrypted storage of my individual answers with my order, for evidence and recovery.",
  needsQuiz: "Deep needs your individual answers. Complete a new test before buying; an old score or share link is not enough.",
  retake: "Take a new test for Deep", upgrade: "Upgrade to Deep", upgradeNote: "Pay US$10 from Personal or US$5 from Plus. Existing features remain yours. If you retake, the original report remains accessible.",
  original: "View original report", latest: "View Deep report", retestNote: "This Deep report uses the answers submitted for the upgrade. Your original report is preserved.",
  evidence: "Why you got these scores", evidenceHelp: "Each answer maps to the left end of its axis on a 0–100 scale. The axis score is the rounded average. A midpoint answer can mean uncertainty or context, not a firm centrist position.",
  chosen: "Your answer", contribution: "Position toward the left pole", neutral: "Neutral / depends answers", insufficient: "Many answers are neutral or depend on context. These matches are reading suggestions, not a confident statement of your political identity.",
  combinations: "How your positions fit together", combinationHelp: "Different axes ask different questions. A gap is not proof of contradiction. Use the actual answers below to check the context.",
  combinationNames: ["Ownership, coordination and trade", "Local power, representation and security", "Religion, social change and culture"],
  combinationQuestions: ["Would your preferred rules change between healthcare, housing and consumer goods? Separate who owns a service from how it is coordinated and traded.", "When would you give local decisions priority, and what rights should remain protected regardless of the majority?", "How do your personal convictions differ from the rules you want public institutions to enforce?"],
  explore: "Explore a different answer", exploreHelp: "Change one answer at a time to see the model respond. This does not edit your saved report and is not a confidence interval or a prediction.", question: "Question", alternative: "Alternative answer", simulate: "Show the change", originalScore: "Saved", changedScore: "Explored", reading: "Your reading and reflection plan", readingHelp: "Prioritized by the axes furthest from the midpoint. These are educational starting points, not endorsements. Sources may be in English.", reason: "Why this topic", reflect: "Before and after reading, write one argument for each pole. Which of your answers would you reconsider, and why?", source: "Read the reference", version: "Question version", busy: "Loading…", error: "Could not load. Please try again.",
  resume: "Continue your saved test", discard: "Delete local test", saved: "Your progress and free result are saved on this browser for 30 days. Anyone using this browser may see them. You can delete them here.", resumeError: "This saved test is unavailable. Please start again.", download: "Download result image", freeResults: "View free results", privateLocal: "Saved only on this browser; paid report links are not saved here.",
  catalog: "Explore reference profiles", search: "Search profiles", query: "Name or category", groups: ["Ideologies", "Countries / regions", "People"], domain: "Match by", domains: ["All 12 axes", "Political", "Social", "Economic"], filter: "Category", filters: { all: "All", current: "Present-day", historical: "Historical", politics: "Politics", philosophy: "Philosophy / religion", science: "Science / technology", arts: "Arts / literature", economics: "Economics", other: "Other" }, furthest: "Furthest matches", empty: "No matching profiles.", directory: "Reference library", libraryHelp: "A small selection from our model catalog. Read the definition and modeled axes before interpreting a match. These profiles are not population averages or verified psychological measurements.", related: "Related profiles", takeTest: "Take the free test", axes: "Modeled axes", readingTopics: ["Federalism", "Democracy", "Liberty", "Immigration", "War and peace", "International justice", "Markets and ownership", "Economic justice", "Globalization", "Religion and politics", "Conservatism and change", "Ethics of technology"],
};
export type DeepCopy = typeof en;
export const deepCopy: Record<Locale, DeepCopy> = {
  en,
  pt: {
    name: "Relatório Deep", amount: "US$14,99", includes: "Tudo do Relatório Plus, mais:", features: ["Evidências das respostas em cada eixo", "Interpretação conjunta dos eixos", "Exploração interativa de outras respostas", "Plano pessoal de leitura e reflexão"], plusExtra: "Busque qualquer perfil; explore países e pessoas por categoria",
    consent: "Para o Deep, também concordo com o armazenamento criptografado das minhas respostas individuais com o pedido, para análise e recuperação.", needsQuiz: "O Deep precisa das respostas individuais. Faça um novo teste antes de comprar; uma pontuação antiga ou um link compartilhado não bastam.", retake: "Fazer novo teste para o Deep", upgrade: "Ampliar para Deep", upgradeNote: "Pague US$10 a partir do Pessoal ou US$5 a partir do Plus. Os recursos atuais continuam disponíveis. Ao refazer, o relatório original é preservado.", original: "Ver relatório original", latest: "Ver relatório Deep", retestNote: "Este relatório Deep usa as respostas enviadas na ampliação. Seu relatório original foi preservado.",
    evidence: "Como suas respostas formaram os resultados", evidenceHelp: "Cada resposta corresponde a uma posição de 0 a 100 em direção ao polo esquerdo. O eixo é a média arredondada. Uma resposta neutra pode indicar dúvida ou contexto, não uma posição centrista firme.", chosen: "Sua resposta", contribution: "Posição em direção ao polo esquerdo", neutral: "Respostas neutras / depende", insufficient: "Muitas respostas são neutras ou dependem do contexto. As correspondências são sugestões de leitura, não uma afirmação segura da sua identidade política.", combinations: "Como suas posições se relacionam", combinationHelp: "Os eixos tratam de questões diferentes. Uma diferença não prova contradição. Confira o contexto nas suas respostas abaixo.", combinationNames: ["Propriedade, coordenação e comércio", "Poder local, representação e segurança", "Religião, mudança social e cultura"], combinationQuestions: ["Suas regras preferidas mudariam entre saúde, habitação e bens de consumo? Separe quem é o proprietário de como o serviço é coordenado e comercializado.", "Quando você daria prioridade às decisões locais, e quais direitos deveriam ser protegidos independentemente da maioria?", "Como suas convicções pessoais diferem das regras que deseja para as instituições públicas?"],
    explore: "Explore outra resposta", exploreHelp: "Altere uma resposta por vez para observar o modelo. Isso não modifica o relatório salvo nem representa intervalo de confiança ou previsão.", question: "Pergunta", alternative: "Resposta alternativa", simulate: "Ver a mudança", originalScore: "Salvo", changedScore: "Explorado", reading: "Seu plano de leitura e reflexão", readingHelp: "Prioriza os eixos mais distantes do ponto médio. São pontos de partida educativos, não recomendações ideológicas. As fontes podem estar em inglês.", reason: "Por que este tema", reflect: "Antes e depois da leitura, escreva um argumento para cada polo. Qual resposta você reconsideraria, e por quê?", source: "Ler a referência", version: "Versão das perguntas", busy: "Carregando…", error: "Não foi possível carregar. Tente novamente.",
    resume: "Continuar teste salvo", discard: "Excluir teste local", saved: "O progresso e o resultado gratuito ficam neste navegador por 30 dias. Quem usar este navegador poderá vê-los. Você pode excluí-los aqui.", resumeError: "Este teste salvo não está disponível. Comece novamente.", download: "Baixar imagem do resultado", freeResults: "Ver resultados gratuitos", privateLocal: "Salvo apenas neste navegador; links privados de relatórios não são salvos aqui.",
    catalog: "Explore perfis de referência", search: "Buscar perfis", query: "Nome ou categoria", groups: ["Ideologias", "Países / regiões", "Pessoas"], domain: "Comparar por", domains: ["Todos os 12 eixos", "Política", "Sociedade", "Economia"], filter: "Categoria", filters: { all: "Todas", current: "Atuais", historical: "Históricos", politics: "Política", philosophy: "Filosofia / religião", science: "Ciência / tecnologia", arts: "Artes / literatura", economics: "Economia", other: "Outros" }, furthest: "Perfis mais distantes", empty: "Nenhum perfil encontrado.", directory: "Biblioteca de referência", libraryHelp: "Uma seleção do nosso catálogo de modelos. Leia a definição e os eixos antes de interpretar uma correspondência. Os perfis não são médias populacionais nem medidas psicológicas validadas.", related: "Perfis relacionados", takeTest: "Fazer o teste gratuito", axes: "Eixos do modelo", readingTopics: ["Federalismo", "Democracia", "Liberdade", "Imigração", "Guerra e paz", "Justiça internacional", "Mercados e propriedade", "Justiça econômica", "Globalização", "Religião e política", "Conservadorismo e mudança", "Ética da tecnologia"],
  },
  es: {
    name: "Informe Deep", amount: "US$14,99", includes: "Todo lo del Informe Plus, más:", features: ["Evidencias de tus respuestas en cada eje", "Interpretación conjunta de los ejes", "Exploración interactiva de otras respuestas", "Plan personal de lectura y reflexión"], plusExtra: "Busca cualquier perfil; explora países y personas por categoría",
    consent: "Para Deep, también acepto guardar cifradas mis respuestas individuales con el pedido para el análisis y la recuperación.", needsQuiz: "Deep necesita tus respuestas individuales. Completa un nuevo test antes de comprar; una puntuación antigua o un enlace compartido no bastan.", retake: "Hacer un nuevo test para Deep", upgrade: "Ampliar a Deep", upgradeNote: "Paga US$10 desde Personal o US$5 desde Plus. Conservas tus prestaciones actuales. Si repites el test, el informe original sigue disponible.", original: "Ver informe original", latest: "Ver informe Deep", retestNote: "Este informe Deep usa las respuestas enviadas al ampliar. Se conserva tu informe original.",
    evidence: "Cómo tus respuestas forman el resultado", evidenceHelp: "Cada respuesta corresponde a una posición de 0 a 100 hacia el polo izquierdo. El eje es el promedio redondeado. Una respuesta neutral puede indicar duda o contexto, no un centrismo firme.", chosen: "Tu respuesta", contribution: "Posición hacia el polo izquierdo", neutral: "Respuestas neutrales / depende", insufficient: "Muchas respuestas son neutrales o dependen del contexto. Las coincidencias son sugerencias de lectura, no una afirmación segura de tu identidad política.", combinations: "Cómo se relacionan tus posiciones", combinationHelp: "Los ejes plantean preguntas diferentes. Una diferencia no demuestra una contradicción. Revisa el contexto en tus respuestas.", combinationNames: ["Propiedad, coordinación y comercio", "Poder local, representación y seguridad", "Religión, cambio social y cultura"], combinationQuestions: ["¿Cambiarían tus reglas entre sanidad, vivienda y bienes de consumo? Separa quién posee un servicio de cómo se coordina y comercializa.", "¿Cuándo priorizarías las decisiones locales y qué derechos protegerías independientemente de la mayoría?", "¿En qué se diferencian tus convicciones personales de las normas que quieres para las instituciones públicas?"],
    explore: "Explora otra respuesta", exploreHelp: "Cambia una respuesta cada vez para observar el modelo. No modifica el informe guardado ni representa un intervalo de confianza o una predicción.", question: "Pregunta", alternative: "Respuesta alternativa", simulate: "Ver el cambio", originalScore: "Guardado", changedScore: "Explorado", reading: "Tu plan de lectura y reflexión", readingHelp: "Prioriza los ejes más alejados del punto medio. Son puntos de partida educativos, no recomendaciones ideológicas. Las fuentes pueden estar en inglés.", reason: "Por qué este tema", reflect: "Antes y después de leer, escribe un argumento para cada polo. ¿Qué respuesta reconsiderarías y por qué?", source: "Leer la referencia", version: "Versión de preguntas", busy: "Cargando…", error: "No se pudo cargar. Inténtalo de nuevo.",
    resume: "Continuar test guardado", discard: "Borrar test local", saved: "Tu progreso y resultado gratuito se guardan en este navegador durante 30 días. Quien use este navegador podrá verlos. Puedes borrarlos aquí.", resumeError: "Este test guardado no está disponible. Empieza de nuevo.", download: "Descargar imagen del resultado", freeResults: "Ver resultados gratuitos", privateLocal: "Solo se guarda en este navegador; no se guardan enlaces privados de informes.",
    catalog: "Explora perfiles de referencia", search: "Buscar perfiles", query: "Nombre o categoría", groups: ["Ideologías", "Países / regiones", "Personas"], domain: "Comparar por", domains: ["Los 12 ejes", "Política", "Sociedad", "Economía"], filter: "Categoría", filters: { all: "Todas", current: "Actuales", historical: "Históricos", politics: "Política", philosophy: "Filosofía / religión", science: "Ciencia / tecnología", arts: "Artes / literatura", economics: "Economía", other: "Otros" }, furthest: "Perfiles más lejanos", empty: "No se encontraron perfiles.", directory: "Biblioteca de referencia", libraryHelp: "Una selección de nuestro catálogo de modelos. Lee la definición y los ejes antes de interpretar una coincidencia. No son promedios poblacionales ni mediciones psicológicas validadas.", related: "Perfiles relacionados", takeTest: "Hacer el test gratuito", axes: "Ejes del modelo", readingTopics: ["Federalismo", "Democracia", "Libertad", "Inmigración", "Guerra y paz", "Justicia internacional", "Mercados y propiedad", "Justicia económica", "Globalización", "Religión y política", "Conservadurismo y cambio", "Ética de la tecnología"],
  },
  ru: {
    name: "Отчёт Deep", amount: "14,99 USD", includes: "Всё из отчёта Plus, а также:", features: ["Обоснование каждой оси вашими ответами", "Совместное толкование нескольких осей", "Интерактивное изменение одного ответа", "Личный план чтения и размышлений"], plusExtra: "Поиск любого профиля; страны и люди по категориям",
    consent: "Для Deep я также согласен на зашифрованное хранение отдельных ответов вместе с заказом для анализа и восстановления.", needsQuiz: "Для Deep нужны отдельные ответы. Пройдите новый тест до оплаты; старых баллов или общей ссылки недостаточно.", retake: "Новый тест для Deep", upgrade: "Перейти на Deep", upgradeNote: "Доплата: 10 USD с Personal или 5 USD с Plus. Текущие возможности сохраняются. После нового теста исходный отчёт остаётся доступен.", original: "Исходный отчёт", latest: "Открыть Deep", retestNote: "Этот Deep использует ответы, отправленные при обновлении. Исходный отчёт сохранён.",
    evidence: "Как ответы сформировали результат", evidenceHelp: "Ответ переводится в положение от 0 до 100 к левому полюсу оси. Балл — округлённое среднее. Нейтральный ответ может означать сомнение или зависимость от контекста, а не твёрдый центризм.", chosen: "Ваш ответ", contribution: "Положение к левому полюсу", neutral: "Нейтрально / зависит от контекста", insufficient: "Многие ответы нейтральны или зависят от контекста. Совпадения — подсказки для чтения, а не уверенное определение вашей политической идентичности.", combinations: "Как связаны ваши позиции", combinationHelp: "Оси описывают разные вопросы. Разница не доказывает противоречие. Проверьте контекст в своих ответах ниже.", combinationNames: ["Собственность, координация и торговля", "Местная власть, представительство и безопасность", "Религия, социальные изменения и культура"], combinationQuestions: ["Изменились бы ваши правила для медицины, жилья и потребительских товаров? Разделите владение, координацию и торговлю.", "Когда местные решения должны иметь приоритет и какие права нужно защищать независимо от большинства?", "Чем ваши личные убеждения отличаются от правил, которые должны соблюдать государственные учреждения?"],
    explore: "Исследуйте другой ответ", exploreHelp: "Измените один ответ и посмотрите реакцию модели. Сохранённый отчёт не меняется. Это не доверительный интервал и не прогноз.", question: "Вопрос", alternative: "Другой ответ", simulate: "Показать изменение", originalScore: "Сохранено", changedScore: "Вариант", reading: "Ваш план чтения и размышлений", readingHelp: "Приоритет у осей, наиболее удалённых от середины. Это учебные отправные точки, а не поддержка идеологий. Источники могут быть на английском.", reason: "Почему эта тема", reflect: "До и после чтения запишите аргумент за каждый полюс. Какой ответ вы бы пересмотрели и почему?", source: "Читать источник", version: "Версия вопросов", busy: "Загрузка…", error: "Не удалось загрузить. Попробуйте ещё раз.",
    resume: "Продолжить сохранённый тест", discard: "Удалить локальный тест", saved: "Прогресс и бесплатный результат сохраняются в этом браузере на 30 дней. Другие пользователи браузера могут их увидеть. Здесь можно удалить запись.", resumeError: "Сохранённый тест недоступен. Начните заново.", download: "Скачать изображение результата", freeResults: "Бесплатные результаты", privateLocal: "Только в этом браузере; приватные ссылки на отчёты здесь не сохраняются.",
    catalog: "Исследуйте профили", search: "Найти профили", query: "Имя или категория", groups: ["Идеологии", "Страны / регионы", "Личности"], domain: "Сравнить по", domains: ["Все 12 осей", "Политика", "Общество", "Экономика"], filter: "Категория", filters: { all: "Все", current: "Современные", historical: "Исторические", politics: "Политика", philosophy: "Философия / религия", science: "Наука / технологии", arts: "Искусство / литература", economics: "Экономика", other: "Другие" }, furthest: "Самые далёкие профили", empty: "Профили не найдены.", directory: "Библиотека профилей", libraryHelp: "Подборка из каталога моделей. Прочитайте описание и оси перед толкованием совпадения. Это не средние значения населения и не проверенные психологические измерения.", related: "Связанные профили", takeTest: "Пройти бесплатный тест", axes: "Оси модели", readingTopics: ["Федерализм", "Демократия", "Свобода", "Иммиграция", "Война и мир", "Международная справедливость", "Рынки и собственность", "Экономическая справедливость", "Глобализация", "Религия и политика", "Консерватизм и изменения", "Этика технологий"],
  },
  zh: {
    name: "深度报告 Deep", amount: "US$14.99", includes: "包含进阶报告 Plus 的全部权益，另加：", features: ["十二轴逐题答案依据", "跨轴立场组合解读", "交互式答案变化探索", "个人阅读与反思计划"], plusExtra: "搜索任意画像，按类别浏览国家与人物",
    consent: "购买 Deep 时，我另行同意将逐题答案与订单关联加密保存，用于依据解读与报告找回。", needsQuiz: "Deep 需要逐题答案。请在购买前完成新测试；旧分数或分享链接无法生成答案依据。", retake: "重新答题，升级 Deep", upgrade: "升级深度报告", upgradeNote: "基础报告补 US$10，Plus 补 US$5。原有权益不变；重新答题升级后，原报告仍可查看。", original: "查看原报告", latest: "查看深度报告", retestNote: "此深度报告使用升级时提交的答案。你的原报告已保留。",
    evidence: "你的分数是如何形成的", evidenceHelp: "每个回答换算为朝向该轴左端的 0–100 位置，轴分数是这些位置的四舍五入平均值。中立回答可能代表不确定或依情境而定，不等于坚定的中间立场。", chosen: "你的回答", contribution: "朝向左端的位置", neutral: "中立／依情境而定的回答", insufficient: "较多回答为中立或依情境而定。匹配适合作为阅读线索，不能据此确定你的政治身份。", combinations: "你的不同立场如何共存", combinationHelp: "不同轴回答不同问题，差异不等于矛盾。请结合下方的实际回答理解其情境。", combinationNames: ["所有制、资源协调与贸易", "地方权力、政治代表与安全", "宗教、社会变迁与文化"], combinationQuestions: ["面对医疗、住房和消费品，你会选择相同的规则吗？区分谁拥有服务、如何协调资源，以及如何交易。", "哪些场景应优先尊重地方决定？无论多数人如何选择，哪些权利都应受到保护？", "你的个人信念，与希望公共机构执行的规则，有哪些区别？"],
    explore: "探索另一种回答", exploreHelp: "每次改变一个回答，查看模型结果如何变化。不会修改已保存的报告，也不代表置信区间、准确率或预测。", question: "题目", alternative: "尝试另一回答", simulate: "查看变化", originalScore: "已保存", changedScore: "探索结果", reading: "你的阅读与反思计划", readingHelp: "优先选取距离中点最远的轴。这些是教育性阅读起点，不代表立场推荐；参考材料可能为英文。", reason: "为什么读这个主题", reflect: "阅读前后各写出一个支持两端立场的理由。你会重新考虑哪一条回答，为什么？", source: "阅读参考资料", version: "题库版本", busy: "正在加载…", error: "加载失败，请重试。",
    resume: "继续已保存的测试", discard: "删除本机测试记录", saved: "进度与免费结果会在此浏览器保存 30 天。使用此浏览器的人可能看到记录，你可在这里删除。", resumeError: "已保存的测试不可用，请重新开始。", download: "下载结果图片", freeResults: "查看免费结果", privateLocal: "仅保存在此浏览器；不会在这里保存付费报告私人链接。",
    catalog: "探索参考画像", search: "搜索画像", query: "名称或类别", groups: ["意识形态", "国家／地区", "人物"], domain: "匹配维度", domains: ["全部十二轴", "政治", "社会", "经济"], filter: "类别", filters: { all: "全部", current: "当代", historical: "历史", politics: "政治", philosophy: "哲学／宗教", science: "科学／技术", arts: "艺术／文学", economics: "经济", other: "其他" }, furthest: "查看最不相似的画像", empty: "未找到对应画像。", directory: "参考画像资料库", libraryHelp: "从本站模型目录精选的参考条目。理解匹配前，请先阅读定义和轴画像。这些数据不是人口平均值，也不是经过验证的心理测量。", related: "相关画像", takeTest: "开始免费测试", axes: "模型轴画像", readingTopics: ["联邦制", "民主", "自由", "移民", "战争与和平", "国际正义", "市场与所有制", "经济正义", "全球化", "宗教与政治", "保守主义与变迁", "技术伦理"],
  },
};

export const compactPlanFeatures: Record<Locale, string[]> = {
  en: ["12 axis readings", "10 ideologies", "Private link + recovery", "Print / PDF", "10 ideology comparisons", "10 countries + 10 people", "Compare a friend", "Search all profiles", "Answer evidence", "Cross-axis reading", "What-if answers", "Reading plan"],
  pt: ["Leitura dos 12 eixos", "10 ideologias", "Link + recuperação", "Imprimir / PDF", "10 comparações ideológicas", "10 países + 10 pessoas", "Comparar amigo", "Buscar perfis", "Evidências das respostas", "Leitura entre eixos", "Simular respostas", "Plano de leitura"],
  es: ["Lectura de 12 ejes", "10 ideologías", "Enlace + recuperación", "Imprimir / PDF", "10 comparaciones ideológicas", "10 países + 10 personas", "Comparar amigo", "Buscar perfiles", "Evidencias de respuestas", "Lectura entre ejes", "Simular respuestas", "Plan de lectura"],
  ru: ["Разбор 12 осей", "10 идеологий", "Ссылка + восстановление", "Печать / PDF", "Сравнение 10 идеологий", "10 стран + 10 людей", "Сравнить с другом", "Поиск профилей", "Обоснование ответами", "Связь осей", "Изменение ответа", "План чтения"],
  zh: ["十二轴解读", "前十意识形态", "私人链接与找回", "打印／PDF", "十种流派逐轴对比", "十国与十人逐轴对比", "与朋友对比", "搜索任意画像", "逐题答案依据", "跨轴组合解读", "答案变化探索", "个人阅读计划"],
};
