import type { Locale } from "./i18n";

type PlusCopy = Record<"basic" | "plus" | "price" | "buy" | "upgrade" | "upgradeNote" | "includes" | "ideology" | "countries" | "people" | "notice" | "details" | "closest" | "furthest" | "axis" | "you" | "reference" | "gap" | "scale" | "friend" | "friendHelp" | "friendInput" | "consent" | "compare" | "busy" | "error" | "friendTarget" | "lengths" | "different", string> & { features: string[] };

export const plusCopy = {
  en: {
    basic: "Personal Report", plus: "Report Plus", price: "US$9.99 once", buy: "Unlock Report Plus · US$9.99", upgrade: "Upgrade this report · US$5.00", upgradeNote: "Already paid US$4.99? Add only the new features for US$5.00. Your original report stays available. Refunding the upgrade removes only the added features; refunding the original purchase also removes upgrade access.",
    includes: "Everything in the US$4.99 report, plus:", features: ["Axis-by-axis comparison with your top 10 ideologies", "Top 10 country profiles and top 10 personalities, with descriptions and axis differences", "Compare all 12 axes with a friend’s freely shared result", "All added comparisons included in the print / PDF view"],
    ideology: "Why these ideologies are close", countries: "Your 10 closest country profiles", people: "Your 10 closest personalities", notice: "Countries and people are reference profiles, not measured population averages or endorsements. Similarity is a model score, not a probability or a relationship assessment.", details: "Compare all 12 axes", closest: "Smallest difference", furthest: "Largest difference", axis: "Axis", you: "You", reference: "Reference", gap: "Difference (percentage points)", scale: "Percentages below refer to the left pole of each axis. A smaller gap means closer scores on that axis; overall ranking uses the full matching model.",
    friend: "Compare with a friend", friendHelp: "Ask your friend to finish the free test and voluntarily send you their public share link. Paste that link below, never a private paid-report link. The comparison is not stored; re-enter the link when you return.", friendInput: "Friend’s public share link", consent: "My friend chose to share this result with me, and I agree to compare it with mine.", compare: "Compare results", busy: "Loading…", error: "Could not compare. Use a valid, unexpired 12Axes public share link and an active Report Plus.", friendTarget: "Friend", lengths: "Question counts (you / friend)", different: "Different question counts can affect the comparison.",
  },
  pt: {
    basic: "Relatório pessoal", plus: "Relatório Plus", price: "US$ 9,99 uma vez", buy: "Desbloquear Plus · US$ 9,99", upgrade: "Ampliar este relatório · US$ 5,00", upgradeNote: "Já pagou US$ 4,99? Adicione apenas os novos recursos por US$ 5,00. Seu relatório original continua disponível. Reembolsar a ampliação remove só os extras; reembolsar a compra original também encerra o acesso à ampliação.",
    includes: "Tudo do relatório de US$ 4,99, mais:", features: ["Comparação por eixo com suas 10 ideologias mais próximas", "10 perfis de países e 10 personalidades, com descrições e diferenças por eixo", "Comparação dos 12 eixos com um resultado compartilhado gratuitamente por um amigo", "Comparações adicionais incluídas na impressão / PDF"],
    ideology: "Por que estas ideologias são próximas", countries: "Seus 10 perfis de países mais próximos", people: "Suas 10 personalidades mais próximas", notice: "Países e pessoas são perfis de referência, não médias populacionais medidas nem recomendações. A similaridade é uma pontuação do modelo, não probabilidade ou avaliação de relacionamento.", details: "Comparar os 12 eixos", closest: "Menor diferença", furthest: "Maior diferença", axis: "Eixo", you: "Você", reference: "Referência", gap: "Diferença (pontos percentuais)", scale: "Os percentuais se referem ao polo esquerdo de cada eixo. Menor diferença indica pontuações mais próximas; a classificação geral usa o modelo completo.",
    friend: "Compare com um amigo", friendHelp: "Peça ao seu amigo para concluir o teste gratuito e enviar voluntariamente o link público do resultado. Cole o link abaixo, nunca um link privado de relatório pago. A comparação não é salva; insira o link novamente ao voltar.", friendInput: "Link público do amigo", consent: "Meu amigo escolheu compartilhar este resultado comigo e concordo em compará-lo com o meu.", compare: "Comparar resultados", busy: "Carregando…", error: "Não foi possível comparar. Use um link público válido e não expirado do 12Axes e um Relatório Plus ativo.", friendTarget: "Amigo", lengths: "Número de perguntas (você / amigo)", different: "Quantidades diferentes de perguntas podem afetar a comparação.",
  },
  es: {
    basic: "Informe personal", plus: "Informe Plus", price: "9,99 USD una vez", buy: "Desbloquear Plus · 9,99 USD", upgrade: "Ampliar este informe · 5,00 USD", upgradeNote: "¿Ya pagaste 4,99 USD? Añade solo las nuevas funciones por 5,00 USD. Conservas tu informe original. Reembolsar la ampliación elimina solo los extras; reembolsar la compra original también elimina el acceso a la ampliación.",
    includes: "Todo el informe de 4,99 USD, más:", features: ["Comparación por eje con tus 10 ideologías más cercanas", "10 perfiles de países y 10 personalidades con descripciones y diferencias por eje", "Comparación de los 12 ejes con el resultado que un amigo comparta gratis", "Comparaciones adicionales incluidas en impresión / PDF"],
    ideology: "Por qué estas ideologías son cercanas", countries: "Tus 10 perfiles de países más cercanos", people: "Tus 10 personalidades más cercanas", notice: "Países y personas son perfiles de referencia, no medias poblacionales medidas ni recomendaciones. La similitud es una puntuación del modelo, no probabilidad ni evaluación de relaciones.", details: "Comparar los 12 ejes", closest: "Menor diferencia", furthest: "Mayor diferencia", axis: "Eje", you: "Tú", reference: "Referencia", gap: "Diferencia (puntos porcentuales)", scale: "Los porcentajes corresponden al polo izquierdo de cada eje. Una diferencia menor indica puntuaciones más cercanas; la clasificación usa el modelo completo.",
    friend: "Compara con un amigo", friendHelp: "Pide a tu amigo que complete el test gratuito y te envíe voluntariamente su enlace público. Pégalo abajo, nunca un enlace privado de informe pagado. La comparación no se guarda; vuelve a introducir el enlace al regresar.", friendInput: "Enlace público de tu amigo", consent: "Mi amigo eligió compartir este resultado conmigo y acepto compararlo con el mío.", compare: "Comparar resultados", busy: "Cargando…", error: "No se pudo comparar. Usa un enlace público de 12Axes válido y vigente y un Informe Plus activo.", friendTarget: "Amigo", lengths: "Cantidad de preguntas (tú / amigo)", different: "Distintas cantidades de preguntas pueden afectar la comparación.",
  },
  ru: {
    basic: "Личный отчёт", plus: "Отчёт Plus", price: "9,99 USD однократно", buy: "Открыть Plus · 9,99 USD", upgrade: "Расширить отчёт · 5,00 USD", upgradeNote: "Уже заплатили 4,99 USD? Добавьте новые функции за 5,00 USD. Исходный отчёт остаётся доступным. Возврат доплаты убирает только дополнения; возврат исходной покупки также прекращает доступ к расширению.",
    includes: "Всё из отчёта за 4,99 USD, а также:", features: ["Сравнение по осям с 10 ближайшими идеологиями", "10 профилей стран и 10 личностей с описаниями и различиями по осям", "Сравнение 12 осей с результатом, которым друг поделился бесплатно", "Все дополнительные сравнения в версии для печати / PDF"],
    ideology: "Почему эти идеологии близки", countries: "10 ближайших профилей стран", people: "10 ближайших личностей", notice: "Страны и люди представлены эталонными профилями, а не измеренными средними населения или рекомендациями. Сходство — показатель модели, не вероятность и не оценка отношений.", details: "Сравнить 12 осей", closest: "Наименьшее различие", furthest: "Наибольшее различие", axis: "Ось", you: "Вы", reference: "Эталон", gap: "Разница (процентные пункты)", scale: "Проценты относятся к левому полюсу оси. Меньший разрыв означает более близкие баллы; общий рейтинг использует полную модель.",
    friend: "Сравнение с другом", friendHelp: "Попросите друга пройти бесплатный тест и добровольно отправить публичную ссылку на результат. Вставьте её ниже, не приватную ссылку платного отчёта. Сравнение не сохраняется; при следующем визите вставьте ссылку снова.", friendInput: "Публичная ссылка друга", consent: "Друг решил поделиться со мной этим результатом, и я согласен сравнить его со своим.", compare: "Сравнить результаты", busy: "Загрузка…", error: "Не удалось сравнить. Нужны действующая публичная ссылка 12Axes и активный отчёт Plus.", friendTarget: "Друг", lengths: "Число вопросов (вы / друг)", different: "Разное число вопросов может повлиять на сравнение.",
  },
  zh: {
    basic: "个人报告", plus: "进阶报告 Plus", price: "一次性 US$9.99", buy: "解锁进阶报告 · US$9.99", upgrade: "升级这份报告 · 补 US$5.00", upgradeNote: "已支付 US$4.99？补 US$5.00 即可增加新功能，原报告权益保留。退还升级款只移除新增功能；退还原订单也会终止升级访问。",
    includes: "包含 US$4.99 报告全部权益，另外增加：", features: ["与前 10 个意识形态逐轴比较，了解相近与分歧之处", "前 10 个国家参考画像、前 10 位人物，含说明及逐轴差异", "与朋友免费分享的结果比较全部 12 轴", "新增比较内容可一并打印／保存 PDF"],
    ideology: "为什么与你的这些意识形态接近", countries: "最接近的 10 个国家参考画像", people: "最接近的 10 位人物", notice: "国家和人物均为参考画像，并非人口实测平均值或推荐。相似度是模型分数，不是概率，也不是人际关系测评。", details: "查看全部 12 轴对比", closest: "差异最小", furthest: "差异最大", axis: "轴", you: "你的分数", reference: "参考分数", gap: "差值（百分点）", scale: "百分比均对应每轴左端。差值越小，表示该轴分数越接近；总排名仍采用完整匹配模型计算。",
    friend: "和朋友对比", friendHelp: "请朋友完成免费测试，并自愿把公开分享链接发给你。在下方粘贴该链接，不要提供付费报告私人链接。对比不另行保存，下次打开需重新输入链接。", friendInput: "朋友的公开分享链接", consent: "朋友自愿向我分享此结果，我同意将它与自己的结果进行比较。", compare: "对比结果", busy: "正在加载…", error: "对比失败，请使用有效且未过期的 12Axes 公开分享链接，并确认进阶报告访问有效。", friendTarget: "朋友的分数", lengths: "题目数量（你／朋友）", different: "题量不同可能影响比较。",
  },
} satisfies Record<Locale, PlusCopy>;
