import type { Locale } from "./i18n";

export const privateLinkLabel: Record<Locale, string> = {
  en: "Copy private report link",
  pt: "Copiar link privado do relatório",
  es: "Copiar enlace privado del informe",
  ru: "Копировать приватную ссылку",
  zh: "复制私人报告链接",
};

export const reportUi = {
  en: { title: "Explore your full report", body: "12-axis reading guide, your top 10 ideology matches, a private report link and a print-friendly PDF view. This is an educational comparison, not a scientific assessment.", button: "Unlock for US$4.99", unlocked: "Your full report", pdf: "Print / save as PDF", consent: "I agree to encrypted storage of my political result linked to my purchase for report delivery, as explained in Privacy.", shareConsent: "Save this political result for one year and let anyone with its share link view it.", currency: "One payment in USD. Your bank may charge conversion fees and taxes. No subscription.", pricing: "Pricing", refund: "Refunds & support", privacy: "Privacy", wait: "Opening checkout…", pending: "Payment confirmation is pending. If you cancelled, you have not unlocked a report. You can retry or recover a paid report below.", retry: "Check payment again", reportError: "This report is unavailable or access was revoked. Use the recovery form or contact support.", checkoutError: "Checkout is unavailable. No payment was taken here. Please try again later.", shareError: "The link could not be saved or copied. Please try again.", recover: "Recover a paid report", email: "Payment email", send: "Email my report links", sent: "If a paid report matches this email, a link will be sent. Check spam too.", failed: "Recovery is unavailable. Please try again later." },
  pt: { title: "Explore seu relatório completo", body: "Guia dos 12 eixos, suas 10 ideologias mais próximas, link privado e versão para salvar em PDF. Comparação educativa, não avaliação científica.", button: "Desbloquear por US$ 4,99", unlocked: "Seu relatório completo", pdf: "Imprimir / salvar em PDF", consent: "Concordo com o armazenamento criptografado do meu resultado político vinculado à compra para entregar o relatório, conforme a Privacidade.", shareConsent: "Salvar este resultado político por um ano e permitir acesso a qualquer pessoa com o link.", currency: "Pagamento único em USD. Seu banco pode cobrar câmbio e tributos. Sem assinatura.", pricing: "Preços", refund: "Reembolso e suporte", privacy: "Privacidade", wait: "Abrindo pagamento…", pending: "A confirmação do pagamento está pendente. Se você cancelou, o relatório não foi desbloqueado. Tente novamente ou recupere uma compra abaixo.", retry: "Verificar pagamento", reportError: "Relatório indisponível ou acesso revogado. Use a recuperação ou fale com o suporte.", checkoutError: "Pagamento indisponível. Nenhuma cobrança foi feita aqui. Tente mais tarde.", shareError: "Não foi possível salvar ou copiar o link. Tente novamente.", recover: "Recuperar relatório pago", email: "Email do pagamento", send: "Enviar meus links", sent: "Se houver um relatório pago neste email, enviaremos o link. Confira o spam.", failed: "Recuperação indisponível. Tente mais tarde." },
  es: { title: "Explora tu informe completo", body: "Guía de los 12 ejes, tus 10 ideologías más cercanas, enlace privado y versión para guardar como PDF. Comparación educativa, no evaluación científica.", button: "Desbloquear por 4,99 USD", unlocked: "Tu informe completo", pdf: "Imprimir / guardar PDF", consent: "Acepto guardar cifrado mi resultado político vinculado a la compra para entregar el informe, según Privacidad.", shareConsent: "Guardar este resultado político un año y permitir que cualquiera con el enlace lo vea.", currency: "Pago único en USD. Tu banco puede cobrar cambio e impuestos. Sin suscripción.", pricing: "Precios", refund: "Reembolsos y ayuda", privacy: "Privacidad", wait: "Abriendo pago…", pending: "La confirmación del pago está pendiente. Si cancelaste, no se desbloqueó el informe. Reintenta o recupera una compra abajo.", retry: "Comprobar pago", reportError: "Informe no disponible o acceso revocado. Usa la recuperación o contacta con soporte.", checkoutError: "Pago no disponible. No se ha cobrado aquí. Inténtalo más tarde.", shareError: "No se pudo guardar o copiar el enlace. Inténtalo de nuevo.", recover: "Recuperar informe pagado", email: "Email del pago", send: "Enviar mis enlaces", sent: "Si hay un informe pagado con este email, enviaremos el enlace. Revisa spam.", failed: "Recuperación no disponible. Inténtalo más tarde." },
  ru: { title: "Полный отчёт", body: "Руководство по 12 осям, 10 ближайших идеологий, приватная ссылка и версия для сохранения в PDF. Образовательное сравнение, а не научная оценка.", button: "Открыть за 4,99 USD", unlocked: "Ваш полный отчёт", pdf: "Печать / сохранить PDF", consent: "Согласен на зашифрованное хранение политического результата, связанного с покупкой, для доставки отчёта согласно политике конфиденциальности.", shareConsent: "Сохранить политический результат на год и открыть его всем, у кого есть ссылка.", currency: "Разовый платёж в USD. Банк может взимать комиссию и налоги. Без подписки.", pricing: "Цены", refund: "Возврат и поддержка", privacy: "Конфиденциальность", wait: "Открываем оплату…", pending: "Ожидается подтверждение платежа. После отмены отчёт не открыт. Повторите проверку или восстановите покупку ниже.", retry: "Проверить платёж", reportError: "Отчёт недоступен или доступ отозван. Восстановите ссылку или обратитесь в поддержку.", checkoutError: "Оплата недоступна. Здесь деньги не списывались. Попробуйте позже.", shareError: "Не удалось сохранить или скопировать ссылку. Повторите попытку.", recover: "Восстановить платный отчёт", email: "Email при оплате", send: "Отправить ссылки", sent: "Если на этот email оформлен оплаченный отчёт, мы отправим ссылку. Проверьте спам.", failed: "Восстановление недоступно. Попробуйте позже." },
  zh: { title: "深入了解完整报告", body: "12 轴阅读指南、前 10 个意识形态匹配、私人报告链接，以及可打印保存为 PDF 的版本。用于教育比较，不是科学测评。", button: "以 US$4.99 解锁", unlocked: "你的完整报告", pdf: "打印 / 保存为 PDF", consent: "我同意将政治倾向结果加密保存并关联此笔购买，以交付报告，详见隐私政策。", shareConsent: "将此政治倾向结果保存一年，并允许持有分享链接的人查看。", currency: "美元一次性付款，无订阅。银行可能另收汇兑费用及税费。", pricing: "定价", refund: "退款与支持", privacy: "隐私", wait: "正在打开结账…", pending: "正在等待支付确认。如果已取消付款，报告尚未解锁。可重新检查，或在下方找回已购买的报告。", retry: "重新检查支付", reportError: "报告不可用或访问权已撤销。请使用找回入口或联系支持。", checkoutError: "结账暂不可用，此处未收取付款。请稍后重试。", shareError: "无法保存或复制分享链接，请重试。", recover: "找回付费报告", email: "付款邮箱", send: "发送报告链接", sent: "如果该邮箱有已付款报告，我们会发送链接，请同时检查垃圾邮箱。", failed: "暂时无法找回，请稍后重试。" },
};

export const axisNotes: Record<Locale, string[]> = {
  en: ["Federalism divides authority across regions; unitarism concentrates it nationally. This scale concerns the distribution of power, not the quality of governance.","Democracy prioritizes public participation and accountability; autocracy concentrates decision making. Institutional choices can differ by context.","Security emphasizes public order and enforcement; liberty emphasizes limits on coercion and individual choice. Your score reflects the trade-off in these questions.","Assimilation emphasizes a common public culture; multiculturalism emphasizes room for distinct traditions. Neither percentage measures attitudes toward any individual.","Militarism favors the use or readiness of armed force; pacifism favors peaceful means. This does not predict how you would judge every conflict.","Non-intervention prioritizes restraint abroad; nationalism emphasizes national interests. These labels simplify several different foreign-policy choices.","Public ownership favors collective control of assets; private ownership favors private control. This axis does not measure personal wealth.","Planning emphasizes coordinated allocation; free markets emphasize decentralized exchange. Real economies combine elements of both.","Protectionism favors domestic trade barriers; globalism favors cross-border exchange. A single score cannot capture every industry or treaty.","Secular governance separates religious authority from the state; religious governance gives faith a public role. This is not a measure of personal belief.","Progressivism favors revising established social norms; traditionalism favors continuity. Views may vary across specific issues.","The technology pole favors technical intervention; the biology pole favors natural limits. The framing is an educational simplification, not a scientific scale."],
  pt: ["O federalismo distribui poder entre regiões; o unitarismo o concentra no nível nacional. O eixo não mede a qualidade do governo.","A democracia enfatiza participação e prestação de contas; a autocracia concentra decisões. As escolhas institucionais dependem do contexto.","Segurança enfatiza ordem e fiscalização; liberdade enfatiza limites à coerção e escolha individual.","Assimilação enfatiza uma cultura pública comum; multiculturalismo preserva espaço para diferentes tradições. Não avalia pessoas individuais.","Militarismo favorece prontidão ou uso de força; pacifismo favorece meios pacíficos. Não prevê sua opinião sobre cada conflito.","Não intervenção enfatiza contenção externa; nacionalismo enfatiza interesses nacionais. São simplificações de escolhas distintas.","Propriedade pública favorece controle coletivo; propriedade privada favorece controle privado. Não mede riqueza pessoal.","Planejamento enfatiza alocação coordenada; livre mercado enfatiza trocas descentralizadas. Economias reais combinam ambos.","Protecionismo favorece barreiras comerciais; globalismo favorece trocas internacionais. O número não resume todos os setores.","Governança secular separa religião e Estado; governança religiosa dá à fé um papel público. Não mede sua fé pessoal.","Progressismo favorece mudanças nas normas sociais; tradicionalismo favorece continuidade. Posições variam por assunto.","O polo tecnológico favorece intervenção técnica; o biológico enfatiza limites naturais. É uma simplificação educativa."],
  es: ["Federalismo: poder repartido entre regiones. Unitarismo: poder nacional concentrado. No mide calidad de gobierno.","Democracia: participación y rendición de cuentas. Autocracia: decisiones concentradas. El contexto importa.","Seguridad: orden y cumplimiento. Libertad: límites a la coerción y elección individual.","Asimilación: cultura pública común. Multiculturalismo: espacio para distintas tradiciones. No juzga individuos.","Militarismo: preparación o uso de fuerza. Pacifismo: medios pacíficos. No predice posturas sobre cada conflicto.","No intervención: contención exterior. Nacionalismo: intereses nacionales. Las etiquetas simplifican decisiones distintas.","Propiedad pública: control colectivo. Propiedad privada: control privado. No mide riqueza personal.","Planificación: asignación coordinada. Mercado libre: intercambio descentralizado. Las economías combinan ambos.","Proteccionismo: barreras comerciales. Globalismo: intercambio internacional. Cada sector puede ser distinto.","Gobierno secular: separación de religión y Estado. Gobierno religioso: papel público de la fe. No mide creencias personales.","Progresismo: revisar normas sociales. Tradicionalismo: continuidad. Las opiniones varían según el tema.","Tecnología: intervención técnica. Biología: límites naturales. Es una simplificación educativa."],
  ru: ["Федерализм распределяет полномочия по регионам, унитаризм концентрирует их в центре. Это не оценка качества управления.","Демократия подчёркивает участие и подотчётность, автократия концентрирует решения. Контекст имеет значение.","Безопасность подчёркивает порядок, свобода — ограничения принуждения и личный выбор.","Ассимиляция подчёркивает общую культуру, мультикультурализм — место для разных традиций. Это не оценка отдельных людей.","Милитаризм допускает готовность или применение силы, пацифизм предпочитает мирные средства. Отдельные конфликты различаются.","Невмешательство подчёркивает внешнюю сдержанность, национализм — национальные интересы. Эти ярлыки упрощают разные решения.","Общественная собственность означает коллективный контроль, частная — частный. Личное богатство не измеряется.","Планирование подчёркивает координацию, свободный рынок — децентрализованный обмен. На практике они сочетаются.","Протекционизм поддерживает торговые барьеры, глобализм — международный обмен. Один балл не описывает все отрасли.","Светское управление отделяет религию от государства, религиозное придаёт вере публичную роль. Личная вера не измеряется.","Прогрессизм поддерживает пересмотр социальных норм, традиционализм — преемственность. Взгляды зависят от вопроса.","Технологический полюс поддерживает техническое вмешательство, биологический — природные ограничения. Это учебное упрощение."],
  zh: ["联邦制强调地区分权，单一制强调全国集中权限。它衡量权力分配偏好，不评价治理好坏。","民主强调参与和问责，威权强调集中决策。具体制度选择仍取决于情境。","安全强调公共秩序与执行，自由强调限制强制和个人选择。分数反映本组题目中的权衡。","同化强调共同公共文化，多元文化强调不同传统的空间。它不是对任何个体的评价。","军事主义倾向以武力或备战应对冲突，和平主义倾向和平手段。不能据此预测每场冲突中的态度。","不干预强调对外克制，民族主义强调国家利益。这些标签简化了多种不同外交选择。","公共所有强调集体控制资产，私营强调私人控制。本轴不衡量个人财富。","计划强调协调分配，自由市场强调分散交换。现实经济通常结合两者。","保护主义强调贸易壁垒，全球主义强调跨国交换。一个数字无法概括所有行业和协定。","世俗治理强调政教分离，宗教治理强调信仰的公共角色。本轴不衡量个人虔诚程度。","进步强调修订既有社会规范，传统强调延续。不同具体议题上的意见可能不同。","科技一端强调技术干预，自然一端强调生物与自然边界。这是教育性简化，不是科学量表。"],
};

export function axisReading(locale: Locale, index: number, leftPercent: number, leftPole: string, rightPole: string) {
  const distance = Math.round(Math.abs(leftPercent - 50) * 10) / 10;
  const pole = leftPercent >= 50 ? leftPole : rightPole;
  const percent = Math.round(Math.max(leftPercent, 100 - leftPercent));
  const balanced = Math.abs(leftPercent - 50) < 7.5;
  const reading = {
    en: balanced ? `Your answers sit close to the midpoint between ${leftPole} and ${rightPole}. The net score does not show a pronounced preference on this axis.` : `Your answers lean toward ${pole} (${percent}%), ${distance} percentage points from the midpoint. This describes your responses on this axis, not the probability that a political label applies to you.`,
    pt: balanced ? `Suas respostas ficam próximas do centro entre ${leftPole} e ${rightPole}. O resultado líquido não indica uma preferência acentuada neste eixo.` : `Suas respostas se inclinam a ${pole} (${percent}%), a ${distance} pontos percentuais do centro. Isso descreve suas respostas neste eixo, não a probabilidade de um rótulo político se aplicar a você.`,
    es: balanced ? `Tus respuestas quedan cerca del centro entre ${leftPole} y ${rightPole}. El resultado neto no muestra una preferencia marcada en este eje.` : `Tus respuestas se inclinan hacia ${pole} (${percent}%), a ${distance} puntos porcentuales del centro. Describe tus respuestas en este eje, no la probabilidad de que una etiqueta política te corresponda.`,
    ru: balanced ? `Ваши ответы близки к середине между ${leftPole} и ${rightPole}. Итоговый балл не показывает выраженного предпочтения на этой оси.` : `Ваши ответы склоняются к ${pole} (${percent}%), на ${distance} процентных пункта от середины. Это описание ответов на данной оси, а не вероятность того, что вам соответствует политический ярлык.`,
    zh: balanced ? `你的回答接近${leftPole}与${rightPole}之间的中点，本轴的净分数未显示明显倾向。` : `你的回答倾向${pole}（${percent}%），距中点 ${distance} 个百分点。这描述的是本轴回答的净倾向，并非你属于某个政治标签的概率。`,
  };
  return reading[locale] + " " + axisNotes[locale][index];
}
